[build-system]
requires = ["scikit-build-core>=0.9", "pybind11>=2.11"]
build-backend = "scikit_build_core.build"

[project]
name = "graph_executor_v2"
version = "0.0.1"
requires-python = ">=3.8"
description = "Minimal GE v2 bindings routed to regemm_epilogue"
